# This is the configuration used to check the rubocop source code.

require:
  - rubocop-rails

AllCops:
  Excludes:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'test/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'Gemfile'
    - 'Rakefile'
    - 'config.ru'
    - 'spec/auth/authorize_api_request_spec.rb'
